package fi.vm.sade.sharedutils;

public enum ValintaResource {
    KOOSTE,
    LASKENTA,
    SIJOITTELU,
    VALINTAPERUSTEET,
    JARJESTYSKRITEERIT,
    HAKIJARYHMA_VALINTATAPAJONO,
    LASKENTAKAAVA,
    VALINTARYHMA,
    HAKIJARYHMA,
    HAKUKOHDE,
    VALINTATAPAJONO,
    VALINNANVAIHE,
    VALINTAKOE,
    SIJOITTELUAKTIVOINTI,
    HAKEMUKSET,
    PISTESYOTTOSERVICE,
    PISTESYOTTOEXTERNALSERVICE,
    VALINTATAPAJONOSERVICE,
    ERILLISHAUNTUONTISERVICE
}
