package fi.vm.sade.sharedutils;

public enum ValintaResource {
    TEMPORARY,
    KOOSTE,
    LASKENTA,
    SIJOITTELU,
    VALINTAPERUSTEET,
    JARJESTYSKRITEERIT,
    HAKIJARYHMA_VALINTATAPAJONO,
    LASKENTAKAAVA,
    VALINTARYHMA,
    HAKIJARYHMA,
    HAKUKOHDE,
    VALINTATAPAJONO,
    VALINNANVAIHE,
    VALINTAKOE,
    SIJOITTELUAKTIVOINTI,
    HAKEMUKSET
}
