package fi.vm.sade.valinta.sharedutils;

public enum ValintaResource {
    KOOSTE,
    LASKENTA,
    SIJOITTELU,
    VALINTAPERUSTEET,
    JARJESTYSKRITEERIT,
    HAKIJARYHMA_VALINTATAPAJONO,
    LASKENTAKAAVA,
    VALINTARYHMA,
    HAKIJARYHMA,
    HAKU,
    HAKUKOHDE,
    VALINTATAPAJONO,
    VALINNANVAIHE,
    VALINTAKOE,
    SIJOITTELUAKTIVOINTI,
    HAKEMUKSET,
    PISTESYOTTOSERVICE,
    PISTESYOTTOEXTERNALSERVICE,
    VALINTATAPAJONOSERVICE,
    ERILLISHAUNTUONTISERVICE,
    DOKUMENTTI
}
