name: "Valinta Sharedutils: - Build and Deploy"
on:
  workflow_dispatch:
  release:
    types: [ created ]
  push:
    paths-ignore:
      - '**.md'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'maven'

      - name: Build
        run: mvn clean package -B

      - name: Deploy
        if: ${{ success() && format('refs/heads/{0}', github.event.repository.default_branch) == github.ref }}
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        run: mvn deploy -B -DskipTests --settings ci-tools/common/maven-settings.xml
